# Generated by Django 4.1.2 on 2022-10-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="image",
            field=models.URLField(default="https:\\picture.com"),
            preserve_default=False,
        ),
    ]
