# Generated by Django 4.1.2 on 2022-10-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_gift_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gift",
            new_name="School",
        ),
    ]
