# Generated by Django 4.1.2 on 2022-10-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_rename_gift_school"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="name",
            new_name="group_name",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="image",
            new_name="group_social_media",
        ),
        migrations.RemoveField(
            model_name="school",
            name="age",
        ),
        migrations.RemoveField(
            model_name="school",
            name="description",
        ),
        migrations.AddField(
            model_name="school",
            name="contact_emails",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school",
            name="group_pillars",
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school",
            name="school_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school",
            name="school_state",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
