# Generated by Django 4.1.2 on 2022-10-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_rename_name_school_group_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="group_name",
            new_name="name",
        ),
    ]
