# Generated by Django 4.1.2 on 2022-10-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_plannedevent_alter_school_group_pillars_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("school", models.CharField(max_length=50)),
                ("city_state", models.CharField(max_length=50)),
                ("founding_date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="plannedevent",
            name="type_of_event",
            field=models.CharField(
                choices=[
                    ("CU", "Cultural"),
                    ("SI", "Sisterhood"),
                    ("SV", "Service"),
                    ("PH", "Philanthropy"),
                    ("SA", "RAINN"),
                ],
                default="CU",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="group_pillars",
            field=models.TextField(max_length=200),
        ),
    ]
