# Generated by Django 4.1.2 on 2022-10-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_chapters_alter_plannedevent_type_of_event_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chapters",
            new_name="Chapter",
        ),
    ]
