# Generated by Django 4.1.2 on 2022-10-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_rename_chapters_chapter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="founding_date",
            new_name="original_founding_date",
        ),
        migrations.AddField(
            model_name="chapter",
            name="recharter_date",
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
