# Generated by Django 4.1.2 on 2022-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0010_rename_founding_date_chapter_original_founding_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="recharter_date",
            field=models.DateField(default=True),
        ),
    ]
